# Generated by Django 4.0.3 on 2023-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('spent_money', models.IntegerField(default=0)),
                ('earned_money', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=100)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
