# Generated by Django 4.0.3 on 2023-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_money', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
                ('day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
