# Generated by Django 4.0.3 on 2023-03-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_ledger_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='balance',
        ),
    ]
