# Generated by Django 4.0.3 on 2023-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='longurl',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='shorturl',
            field=models.CharField(max_length=128),
        ),
    ]
