# Generated by Django 4.0.3 on 2023-03-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_urlshortener_longurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortened_url', models.CharField(max_length=50, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='urlShortener',
        ),
    ]
