# Generated by Django 4.0.3 on 2023-03-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_shortenedurl_delete_urlshortener'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('new_link', models.URLField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='ShortenedURL',
        ),
    ]
