# Generated by Django 4.0.3 on 2023-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_url_delete_shortenedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='url',
            name='new_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
